# Generated by Django 4.2.7 on 2023-11-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('theme', models.CharField(blank=True, max_length=25, null=True)),
                ('recommends', models.CharField(blank=True, max_length=25, null=True)),
                ('prepared', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name_plural': 'menu',
                'ordering': ['-date'],
            },
        ),
    ]
