# Generated by Django 4.2.7 on 2023-11-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_fooditem_foodmenu_delete_foods_fooditem_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_fooditem', to='app_admin.foodmenu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
