# Generated by Django 3.2.24 on 2024-03-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_alter_menu_prepared_alter_menu_recommends_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'ordering': ['date', 'category_id']},
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.category'),
        ),
    ]
