# Generated by Django 3.2.24 on 2024-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_auto_20240307_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.CharField(max_length=250),
        ),
    ]
